Smarter download status check and options

diff --git a/scripts/automate-ubuntu b/scripts/automate-ubuntu
--- a/scripts/automate-ubuntu
+++ b/scripts/automate-ubuntu
@@ -3,29 +3,29 @@
 #set -e
 set +x
 
-MIRROR_HOSTNAME=${MIRROR_HOSTNAME:-old-releases.ubuntu.com}
+MIRROR_HOSTNAME=${MIRROR_HOSTNAME:-releases.ubuntu.com}
 MIRROR_DIRECTORY=${MIRROR_DIRECTORY:-/releases}
 MIRROR_PREFIX="http://${MIRROR_HOSTNAME}${MIRROR_DIRECTORY}"
 
 function usage() {
-  local usage="Usage: `basename $0` <release> [-t server_desktop_type]"
+  local usage="Usage: `basename $0` [-r release] [-t server_desktop_type] [-a arch]"
   echo $usage
+  exit
 }
 
-RELEASE=$1
-shift
-if [[ -z "$RELEASE" ]]; then
-  echo "Please input release number"
-  echo $usage
-  #exit
-fi
-
-while [[ $# -gt 0  ]]
-do
-  local key="$1"
+while [[ $# -gt 0  ]]; do
+  key="$1"
   case $key in
+    -r|--release)
+    RELEASE="$2"
+    shift
+    ;;
     -y|--release-type)
     RELEASE_TYPE="$2"
+    shift
+    ;;
+    -a|--arch)
+    RELEASE_ARCH="$2"
     shift
     ;;
     -h|--help)
@@ -41,13 +41,27 @@ if [[ -n "$help" ]]; then
   exit
 fi
 
+if [[ -z "$RELEASE" ]]; then
+  RELEASE="14.04.5"
+fi
+
 if [[ -z "$RELEASE_TYPE" ]]; then
   RELEASE_TYPE="desktop"
 fi
 
-iso_download_url=${MIRROR_PREFIX}/${RELEASE}/ubuntu-${RELEASE}-${RELEASE_TYPE}-amd64.iso
+if [[ -z "$RELEASE_ARCH" ]]; then
+  RELEASE_ARCH="amd64"
+fi
 
-temp=$(mktemp)
-echo "Begin to download image"
-wget -q -O $temp $iso_download_url
-echo "Done"
+iso_name="ubuntu-${RELEASE}-${RELEASE_TYPE}-${RELEASE_ARCH}.iso"
+iso_download_url=${MIRROR_PREFIX}/${RELEASE}/$iso_name
+
+temp=$(mktemp -d)
+echo "Begin to download image to $temp"
+wget -O $temp/${iso_name} $iso_download_url
+if [[ "$?" -ne 0 ]]; then
+  echo "Failed to download the image from ${iso_download_url}"
+else
+  echo "${iso_download_url} is downloaded under ${temp}"
+  echo "Done"
+fi
